### ISSUE TITLE
Parser for XLSX is not installed

### ISSUE THREAD

**Issue by mohit162009** [legoritma/ipxact-register-generator#1]
Hello ,
I am trying to run this script and I am getting following error:

Uncaught exception from user code:
        Parser for XLSX is not installed at ./main.pl line 42
 at /home/nxf36037/ipxact-register-generator-master/code/perl5/lib/perl5/Spreadsheet/Read.pm line 416
        Spreadsheet::Read::ReadData('reg1000.xlsx') called at ./main.pl line 42

I am working on a hosted Linux and I don't have permission to install any modules to Perl. But as I can see all the required libraries are already there in the project directory. Hence I feel something is missing. Kindly look into this issue.

Thanks ,
Mohit

**Comment by g-lesssard** [comment]
Hi,

I imagine that 4 years later, you might either have abandoned this or found the fix by yourself, but for other users who might be interested in this tool, I will provide the fix to get it working. This was tested using perl v5.30, so depending on your version, these might not complete.

The tool needs two packages to read the xlsx files, `Spreadsheet::Read` and `Spreadsheet::ParseXLSX` as well as `Template`, that can all be installed with cpan. Also, you might need to comment lines 8 and 9 from the main.pl file if you get some errors.

**Comment by legoritma** [comment]
Hi,

Sorry for the Radio Silence. I completely forgot this repository. Thanks for reminding @g-lesssard 

I added a new branch for docker support. I hope the steps will be helpful for other user who might interested.

Closing issue
